name: Check series from content

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get content migration branch
        uses: actions/checkout@v4
        with:
          ref: content-migration

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check series content
        run: python import_series.py
