name: Check image migration

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get content migration branch
        uses: actions/checkout@v4
        with:
          ref: content-migration

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check image migration
        run: python migrate_images.py
